# Info about you
name: Marcos Benício
position: M.sc in Physics 
email: marcosbenicio0102@gmail.com
company_name: none
company_url: none
place_name: Niterói, RJ

# Blog info
title: Marcos Benício
description: Blog
url: https://marcosbenicio.github.io/
main_github_io: false
long_description: >-
    Hi!  Welcome to the my blog.

# Social links
github_url: https://github.com/marcosbenicio
linkedin_url: https://linkedin.com/in/marcos-benício-de-andrade-alonso-415a5b16b
social:
  links:
    - https://linkedin.com/in/marcos-benício-de-andrade-alonso-415a5b16b
    - https://github.com/marcosbenicio

# Images + files
logo: assets/img/profile_photo.png
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: auto  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
