# Info about you
name: Marcos Benício
position: M.sc in Physics 
email: marcosbenicio0102@gmail.com
#company_name: none
#company_url: none
place_name: Niterói, RJ

# Blog info
title: Marcos Benício
description: Blog
url: https://marcosbenicio.github.io/
main_github_io: true
long_description: "Welcome to my blog! Here I talk about mathematics, physics, deep learning and machine learning.  
You can find some articles about these concepts. 
I hope you enjoy and don't forget to leave a reaction or comment at the end of the posts! This helps me to improve the content."

# Social links
github_url: https://github.com/marcosbenicio
linkedin_url: https://linkedin.com/in/marcos-benício-de-andrade-alonso-415a5b16b
social:
  links:
    - https://linkedin.com/in/marcos-benício-de-andrade-alonso-415a5b16b
    - https://github.com/marcosbenicio

# Images + files
logo: /assets/img/profile_photo.png
cv_url: /assets/files/cv.pdf
resume_url: /assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: auto  # auto, light, or dark
comments: true
disqus_shortname: none
mathjax:
  enable: true
  src: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
syntax_highlight_stylesheet: syntax_highlight.css


# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
#colors_dark:
  #background: 333
  #text: ccc
  #tag: 2e6830
  #tag_hover: 93cf95
  #header_background: 232 
  #header_text: 93cf95
  #header_link: 93cf95
  #header_link_hover: 459c48
  #links: 459c48
  #links_visited: 357a38

#colors_dark:
#  background: 333
#  text: DEDED6
#  tag: 9A5E56
#  tag_hover: BB6E67
#  header_background: A44640
#  header_text: E5E2D8
#  header_link: F2BBA7
#  header_link_hover: BB6864
#  links: C0867A
#  links_visited: A65F59

#colors_dark:
#  background: 333
#  text: DEE5E9
#  tag: 4A6E9A
#  tag_hover: 6A8EBB
#  header_background: 3A527B
#  header_text: E9ECF0
#  header_link: 8BAAD2
#  header_link_hover: 678CB4
#  links: 6A87B1
#  links_visited: 576D95

colors_dark:
  background: 333
  text: DEE5E9
  tag: 2A4569       
  tag_hover: 3A5579 
  header_background: 3A527B
  header_text: 9dd2f5 #AEBDC7  
  header_link: 9dd2f5 #5A7089 
  header_link_hover: 6A80A1  
  links: 9dd2f5      
  links_visited: 4A6079  





 

