
ûroot"_tf_keras_model*˛{"name": "bnn_regressor", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "BNNRegressor", "config": {"name": "bnn_regressor", "total_samples": 390442, "layers": [1024, 512, 128, 64, 32]}, "shared_object_id": 0, "build_input_shape": {"class_name": "TensorShape", "items": [null, 7]}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 7]}, "float32", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 7]}, "float32", "input_1"]}, "keras_version": "2.14.0", "backend": "tensorflow", "model_config": {"class_name": "BNNRegressor", "config": {"name": "bnn_regressor", "total_samples": 390442, "layers": [1024, 512, 128, 64, 32]}}, "training_config": {"loss": null, "metrics": null, "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Custom>Adam", "config": {"name": "Adam", "weight_decay": null, "clipnorm": null, "global_clipnorm": null, "clipvalue": null, "use_ema": false, "ema_momentum": 0.99, "ema_overwrite_frequency": null, "jit_compile": false, "is_legacy_optimizer": false, "learning_rate": 9.999999747378752e-05, "beta_1": 0.9, "beta_2": 0.999, "epsilon": 1e-07, "amsgrad": false}}}}2
√root.train_elbo_tracker"_tf_keras_metric*ç{"class_name": "Mean", "name": "train_elbo", "dtype": "float32", "config": {"name": "train_elbo", "dtype": "float32"}, "shared_object_id": 1}2
Õ	root.train_mae_tracker"_tf_keras_metric*ò{"class_name": "MeanAbsoluteError", "name": "train_mae", "dtype": "float32", "config": {"name": "train_mae", "dtype": "float32"}, "shared_object_id": 2}2
Ω
root.val_elbo_tracker"_tf_keras_metric*â{"class_name": "Mean", "name": "val_elbo", "dtype": "float32", "config": {"name": "val_elbo", "dtype": "float32"}, "shared_object_id": 3}2
«root.val_mae_tracker"_tf_keras_metric*î{"class_name": "MeanAbsoluteError", "name": "val_mae", "dtype": "float32", "config": {"name": "val_mae", "dtype": "float32"}, "shared_object_id": 4}2
¨root.loc_net"_tf_keras_model*Ç{"name": "BayesianNN", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "BNN", "config": {"name": "BayesianNN", "layer_units": [1024, 512, 128, 64, 32], "activation_func": "relu"}, "shared_object_id": 5, "build_input_shape": {"class_name": "TensorShape", "items": [null, 7]}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 7]}, "float32", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 7]}, "float32", "input_1"]}, "keras_version": "2.14.0", "backend": "tensorflow", "model_config": {"class_name": "BNN", "config": {"name": "BayesianNN", "layer_units": [1024, 512, 128, 64, 32], "activation_func": "relu"}}}2
ˆcroot.loc_net.layer_list.0"_tf_keras_layer*ø{"name": "DenseVariational_0", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "DenseFlipout", "config": {"name": "DenseVariational_0", "units": 1024, "activation": "relu"}, "shared_object_id": 6, "build_input_shape": {"class_name": "TensorShape", "items": [null, 7]}}2
¯droot.loc_net.layer_list.1"_tf_keras_layer*¡{"name": "DenseVariational_1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "DenseFlipout", "config": {"name": "DenseVariational_1", "units": 512, "activation": "relu"}, "shared_object_id": 7, "build_input_shape": {"class_name": "TensorShape", "items": [null, 1024]}}2
˜eroot.loc_net.layer_list.2"_tf_keras_layer*¿{"name": "DenseVariational_2", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "DenseFlipout", "config": {"name": "DenseVariational_2", "units": 128, "activation": "relu"}, "shared_object_id": 8, "build_input_shape": {"class_name": "TensorShape", "items": [null, 512]}}2
ˆfroot.loc_net.layer_list.3"_tf_keras_layer*ø{"name": "DenseVariational_3", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "DenseFlipout", "config": {"name": "DenseVariational_3", "units": 64, "activation": "relu"}, "shared_object_id": 9, "build_input_shape": {"class_name": "TensorShape", "items": [null, 128]}}2
ˆgroot.loc_net.layer_list.4"_tf_keras_layer*ø{"name": "DenseVariational_4", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "DenseFlipout", "config": {"name": "DenseVariational_4", "units": 32, "activation": "relu"}, "shared_object_id": 10, "build_input_shape": {"class_name": "TensorShape", "items": [null, 64]}}2
Âhroot.loc_net.layer_list.5"_tf_keras_layer*Æ{"name": "OutputLayer", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "preserve_input_structure_in_config": false, "autocast": true, "class_name": "DenseFlipout", "config": {"name": "OutputLayer", "units": 1, "activation": null}, "shared_object_id": 11, "build_input_shape": {"class_name": "TensorShape", "items": [null, 32]}}2